version: '3'

services:
  php:
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./your_php_app:/var/www/html

  mysql:
    build:
      context: .
      dockerfile: .Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: formation
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password

volumes:
  mysql_data:
